RotaProj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('hoursCalc.urls')),
    path('blog/', include('blog.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views as blog_views
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from django.contrib.auth import views as auth_views

# app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name="blog-home"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_detail"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('post/new/', PostCreateView.as_view(), name="post_create"),
    path('todo/', blog_views.todo_list, name="todo_list"),
    path('deu/', blog_views.deu, name='deu'),
    path('jaime/', blog_views.jaime, name='jaime'),
    path('pequenodiu/', blog_views.pequenodiu, name='pequenodiu'),

]

hoursCalc/urls.py
from django.contrib import admin
from django.urls import path
from . import views as shift_views
from django.contrib.auth import views as auth_views

# app_name = 'rota'

urlpatterns = [
    path('', shift_views.initial_page, name="initial_page"),
    path('turnos', shift_views.index, name="index"),
    path('submit/', shift_views.submitForm, name='submit'),
    path('select/', shift_views.selectDate, name='select'),
    path('edit/<int:pk>/', shift_views.update_shift, name='edit'),
    path('detail/<int:pk>/', shift_views.shift_detail, name='detail'),
    path('remove/<int:pk>/', shift_views.remove, name='remove'),
    path('select/<str:date_from>/<str:date_to>/', shift_views.select_periods, name='select'),


    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

hoursCalc/models.py
from django.db import models
import datetime
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User


class Shift(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    clock_in = models.DateTimeField(
        blank=True, null=True)  
    clock_out = models.DateTimeField(
        blank=True, null=True)  
    date = models.DateField(blank=True, null=True)  # não branco ou nulo
    description = models.TextField(blank=True, null=True, max_length=600)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        
        super(Shift, self).save(*args, **kwargs)

hoursCalc/forms.py
from django import forms
from .models import Shift
# from django.contrib.auth.models import User


class ClockInOutForm(forms.ModelForm):  #shiftForm 
  clock_in = forms.TimeField(label='Inicio ', 
                             widget=forms.TimeInput( 
                             attrs={"class":"form-control", "placeholder":"horas:min:seg"})) 
  
  clock_out = forms.TimeField(label='fim', 
                              widget=forms.TimeInput(
                              attrs={"class":"form-control", "placeholder":"horas:min:seg"}))

  

  date = forms.DateField(widget=forms.SelectDateWidget(attrs={"class":""}))

  class Meta():
    model = Shift 
    fields = ['description']


class SelectDateForm(forms.Form):
  date_from = forms.DateField(widget=forms.SelectDateWidget(attrs={"class": "",}, ), label="From")
  date_to = forms.DateField(widget=forms.SelectDateWidget(attrs={"class": "",}), label="To")


class ShiftUpdateForm(forms.Form):
  clock_in = forms.TimeField(label='Inicio ', 
                             widget=forms.TimeInput( 
                             attrs={"class":"form-control", "placeholder":"hour:min:sec"})) 
  
  clock_out = forms.TimeField(label='Fim', 
                              widget=forms.TimeInput(
                              attrs={"class":"form-control", "placeholder":"hour:min:sec"}))

 

  date = forms.DateField(widget=forms.SelectDateWidget(attrs={"class":""}))

hoursCalc/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from . import forms
from .models import Shift

# from django.db.models import Sum, Count


def initial_page(request):
    return render(request, 'hoursCalc/initial_page.html')

#aqui tem um login requirido

def index(request):

    users = User.objects.all()
    form = forms.ClockInOutForm()
    shift = Shift.objects.all()

    context = {
        'shift': shift,
        'users': users,
        'form': form,
        'title': 'Home'
    }

    return render(request, 'hoursCalc/index.html', context)


@login_required
def submitForm(request):  # mudar para

    if request.method == 'POST':
        form = forms.ClockInOutForm(request.POST)

        if form.is_valid():

            name = request.user

            new_clock_in = str(
                form.cleaned_data['date']) + ' ' + str(form.cleaned_data['clock_in'])
            new_clock_out = str(
                form.cleaned_data['date']) + ' ' + str(form.cleaned_data['clock_out'])

            clock_in_new = datetime.strptime(new_clock_in, '%Y-%m-%d %H:%M:%S')
            clock_out_new = datetime.strptime(
                new_clock_out, '%Y-%m-%d %H:%M:%S')

            Shift.objects.create(name=name,
                                 clock_in=clock_in_new,
                                 clock_out=clock_out_new,
                                 date=form.cleaned_data['date'],
                                 description=form.cleaned_data['description'])

    return redirect(index)


@login_required
def remove(request, pk):  # mudar remover
    post = get_object_or_404(Shift, pk=pk)

    user_post_id = post.name.id
    request_user_id = request.user.id

    if(user_post_id != request_user_id):
        messages.warning(request, f'você não poder deletar, porque não foi voce que o fez')
        return redirect(index)

    post.delete()
    messages.success(request, f'você removeu')
    return redirect(index)

#aqui tem um login requirido

# juntar selectDate com select_periods
def selectDate(request, dt="2000-01-01", df="2000-01-01"):

    users = User.objects.all()
    select_date_form = forms.SelectDateForm()
    shifts = Shift.objects.select_related('name').order_by('name')

    if request.method == 'POST':
        select_date_form = forms.SelectDateForm(request.POST)

        if select_date_form.is_valid():

            print("VALIDATION SUCCESS!")
            print("date_from: ", select_date_form.cleaned_data['date_from'])
            print("date_to: ", select_date_form.cleaned_data['date_to'])

            df = select_date_form.cleaned_data['date_from']
            dt = select_date_form.cleaned_data['date_to']

            shifts = Shift.objects.select_related('name').filter(
                date__gte=df, date__lte=dt).order_by('name')

    context = {
        'select_date_form': select_date_form,
        'users': users,
        'shifts': shifts,
        'title': 'Select Dates'
    }

    return render(request, 'hoursCalc/select.html', context)


#aqui tem um login requirido

def select_periods(request, date_from, date_to):  # filtrar as datas dos turnos 
    users = User.objects.all()
    objects = Shift.objects.filter(
        date__gte=date_from).filter(date__lte=date_to)

    context = {
        'users': users,
        'objects': objects,
        'title': 'Select Period'
    }

    return render(request, 'hoursCalc/select.html', context)


@login_required
def update_shift(request, pk):  # Atualiza o shift o turno

    shift_to_update = get_object_or_404(Shift, pk=pk)

    if request.method == 'POST':
        shift_form = forms.ShiftUpdateForm(request.POST)

        if shift_form.is_valid():

            new_clock_in = str(
                shift_form.cleaned_data['date']) + ' ' + str(shift_form.cleaned_data['clock_in'])
            new_clock_out = str(
                shift_form.cleaned_data['date']) + ' ' + str(shift_form.cleaned_data['clock_out'])

            clock_in_new = datetime.strptime(new_clock_in, '%Y-%m-%d %H:%M:%S')
            clock_out_new = datetime.strptime(
                new_clock_out, '%Y-%m-%d %H:%M:%S')

            shift_to_update.clock_in = clock_in_new
            shift_to_update.clock_out = clock_out_new
            shift_to_update.date = shift_form.cleaned_data['date']

            shift_to_update.save()

            messages.success(request, f'Turno atualizado')

            return redirect(index)

    else:
        shift_form = forms.ShiftUpdateForm(initial={'clock_in': shift_to_update.clock_in,
                                                    'clock_out': shift_to_update.clock_out,
                                                    'date': shift_to_update.date,
                                                
                                                    
                                                    'description': shift_to_update.description,
                                                    })

    context = {
        'shift_form': shift_form,
        'title': 'Update Shift'
    }

    return render(request, 'hoursCalc/update_shift.html', context)


def shift_detail(request, pk):
    shift = get_object_or_404(Shift, pk=pk)
    return render(request, 'hoursCalc/shift_detail.html', {'shift': shift})

hoursCalc/templates/hoursCalc/base.html
% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/hoursCalc/cssindex/style.css">
    <link rel="icon" href="static\hoursCalc\imagesindex\bus.png" type="image/png" sizes="16x16">
    <meta name="theme-color" content="#343A40" />

    {% if title %}
    <title> {{ title }} </title>
    {% else %}
    <title> IF∫BUS </title>
    {% endif %}

</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top"><a class="nav-link navbar-brand" href="/"><img
                src="\static\hoursCalc\imagesindex\bus.png" style="height:1em;"><span class="ml-2"><a
                    class="navbar-brand mr-4" href="{% url 'initial_page' %}">IF∫Bus</a>
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                        aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">

                            <a class="nav-item nav-link" href="{% url 'index' %}">Turnos</a>
                            <a class="nav-item nav-link" href="{% url 'select' %}"> Datas</a>
                            <a class="nav-item nav-link" href="{% url 'blog-home' %}"> Quadro de notícias</a>


                            <a class="nav-item nav-link" href="{% url 'todo_list' %}"> Rotas</a>



                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'post_create' %}">Nova postagem</a>
                            <a class="nav-item nav-link" href="{% url 'profile' %}">Perfil</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Sair</a>
                            {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Conecte-se</a>
                           
                            {% endif %}
                        </div>
                    </div>
                </div>
    </nav>
    <div class="container">
        <br>
        <br>
        <br>
        {% block content %}

        {% endblock content %}
    </div>

    <!--Footer-->
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Serviços</h3>
                        <ul>
                            <li><a href="#">Quadro de Noticias</a></li>
                            <li><a href="#">Turnos e Horarios</a></li>
                            <li><a href="#">Rotas e Mapas</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Sobre</h3>
                        <ul>
                            <li><a href="#">Projeto</a></li>
                            <li><a href="#">Time</a></li>
                            <li><a href="#">Apoiadores</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>IF_BUS</h3>
                        <p>Sistema responsável por gerenciar as viagens dos alunos ao IF Campus Guanambi.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i
                                class="icon ion-social-twitter"></i></a><a href="#"><i
                                class="icon ion-social-snapchat"></i></a><a href="#"><i
                                class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Copyright IF_BUS © 2022</p>
            </div>
        </footer>
    </div>
    </footer>

    <style>
        .footer-dark {
            grid-row-start: 2;
            grid-row-end: 3;
            padding: 50px 0;
            color: #f0f9ff;
            background-color: #282d32;
        }

        .footer-dark h3 {
            margin-top: 0;
            margin-bottom: 12px;
            font-weight: bold;
            font-size: 16px;
        }

        .footer-dark ul {
            padding: 0;
            list-style: none;
            line-height: 1.6;
            font-size: 14px;
            margin-bottom: 0;
        }

        .footer-dark ul a {
            color: inherit;
            text-decoration: none;
            opacity: 0.6;
        }

        .footer-dark ul a:hover {
            opacity: 0.8;
        }

        @media (max-width:767px) {
            .footer-dark .item:not(.social) {
                text-align: center;
                padding-bottom: 20px;
            }
        }

        .footer-dark .item.text {
            margin-bottom: 36px;
        }

        @media (max-width:767px) {
            .footer-dark .item.text {
                margin-bottom: 0;
            }
        }

        .footer-dark .item.text p {
            opacity: 0.6;
            margin-bottom: 0;
        }

        .footer-dark .item.social {
            text-align: center;
        }

        @media (max-width:991px) {
            .footer-dark .item.social {
                text-align: center;
                margin-top: 20px;
            }
        }

        .footer-dark .item.social>a {
            font-size: 20px;
            width: 36px;
            height: 36px;
            line-height: 36px;
            display: inline-block;
            text-align: center;
            border-radius: 50%;
            box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.4);
            margin: 0 8px;
            color: #fff;
            opacity: 0.75;
        }

        .footer-dark .item.social>a:hover {
            opacity: 0.9;
        }

        .footer-dark .copyright {
            text-align: center;
            padding-top: 24px;
            opacity: 0.3;
            font-size: 13px;
            margin-bottom: 0;
        }
    </style>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

hoursCalc/templates/hoursCalc/index.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container mb-4">
    <h1 class="display-3">
        <center>Turnos</center>
    </h1>
    <button type="button" class="btn btn-info btn-lg btn-block" data-toggle="modal" data-target="#filterModal">Adiciona novo turno</button>
</div>

<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
</div>

<div class="container">

    {% load shifts %} {# custom tag #}

    <div class="container">
        {% for user in users %}
        {% if user.shift_set.count > 0 %}
        <div class="row"> {# this could be a nav that stick intil the next one? #}
            <div class="col-md-2">
                {# <img class="rounder-circle" src="{{ user.profile.image.url}}" alt="">#}
                <strong>{{user.username}}</strong>
            </div>
            <div class="col-md-2"> <strong> inicio/Parada </strong> </div>
            
           
            <div class="col-md-3"> </div>
        </div>
        <hr>
        {% for i in user.shift_set.all %} 
        <div class="row">
            <div class="col-md-2"> {{ i.date|date:"" }} </div>
            <div class="col-md-2"> {{ i.clock_in|date:"H:i" }} - {{ i.clock_out|date:"H:i"}} </div>
            
            
            <div class="col-md-1"> <a class="btn btn-outline-info btn-sm" href="{% url 'detail' pk=i.id %}">Detalhe</a>
            </div>
            <div class="col-md-1"> <a class="btn btn-outline-info btn-sm" href="{% url 'edit' pk=i.id %}">Editar</a>
            </div>
            <div class="col-md-1"> <a class="btn btn-outline-danger btn-sm"
                    href="{% url 'remove' pk=i.id %}">Remover</a> </div>
        </div>
        <hr>

        {% endfor %}

        <div class="row">
            <div class="col-md-2"> </div>
            <div class="col-md-2"> </div>
            <div class="col-md-2"> </div>

            

            <div class="col-md-3"> </div>
        </div>
        <hr>
        {% else %}
        {% endif %}
        {% endfor %}

    </div>


    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Novo Turno</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'submit' %}" method="POST">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <hr>
                        <input type="submit" class="btn btn-primary" value="Submit">
                        {#<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>#}
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock content %}

hoursCalc/templates/hoursCalc/initial_page.html
{% extends './base.html' %}

{% block content %}

<div class="my-5"></div>
<header class="masthead">
    <div class="container h-100" src="static\hoursCalc\imagesindex\masthead-bg.jpeg.svg">
        <div class="row h-100 align-items-center">
            <div class="col-12 text-center text-white">
                <h1>IF∫Bus</h1>
                <p class="lead">Destino único para sua viagem de ônibus</p>
                <div>
                    <a class="btn btn-primary mx-2 my-2" href="{% url 'index' %}">Turnos</a>
                    <a class="btn btn-light mx-2 my-2" href="{% url 'select' %}"> Filtros de viagem</a>
                    <a class="btn btn-light mx-2 my-2" href="{% url 'blog-home' %}"> Quadro de notícias</a>
                    <a class="btn btn-light mx-2 my-2" href="{% url 'todo_list' %}"> Rotas</a>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-4">
            <h2 class="text-center">Adicione Turnos</h2><img class="landing-icon d-block mx-auto my-4"
                src="\static\hoursCalc\imagesindex\directions.svg">
            <p class="h-25">
                Com um clique, você pode adicionar um turno a sua viagem em nosso site.
                Isso economizará tempo e aborrecimentos no ônibus para que você possa aproveitar seu passeio.
            
        </div>

        <div class="col-sm-4">
            <h2 class="text-center">Avisos de Motoristas</h2><img class="landing-icon d-block mx-auto my-4"
                src="\static\hoursCalc\imagesindex\ticket.svg">
            <p class="h-25">
                Apartir do nosso sistema e possivel vizualizar avisos dos onibus, informado sobre algo de importante
                como rodagem em sabados letivos, comprovantes, objetos perdidos, trocas de onibus em rodagem e etc.
            
        </div>

        <div class="col-sm-4">
            <h2 class="text-center">Visualize Pontos</h2><img class="landing-icon d-block mx-auto my-4"
                src="\static\hoursCalc\imagesindex\location.svg">
            <p class="h-25">
                Não sabe as rotas do seu ônibus? Acompanhe a trajetoria do seu ônibus em nosso site.
                Sempre saiba onde seu ônibus passará para que você possa estar preparado.
           
        </div>
    </div>
</div>

{% endblock content %}

hoursCalc/templates/hoursCalc/select.html
{% extends './base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <h1 class="display-3">
        <center>Filtrar datas</center>
    </h1>
</div>

<div class="container">
    <div class="jumbotron">

        <form action={% url 'select' %} method="POST">
            {% csrf_token %}
            <center>
                {{ select_date_form }}
                <input type="submit" class="btn btn-outline-danger btn-sm" value="Select">
            </center>
        </form>

    </div>

</div>

<div class="container">
    {% regroup shifts by name as user_list %}
    {% load shifts %} {# custom tag #}

    <hr>
    {% for user in user_list %}

    <div class="row">
        <div class="col-md-2"> <strong>{{ user.grouper.username }}</strong> </div>
        <div class="col-md-2"> <strong> Entrada/Saída </strong> </div>
       
        
        <div class="col-md-3"> </div>
    </div>
    <hr>
    {% for shift in user.list %}
    <div class="row">
        <div class="col-md-2"> {{ shift.date|date:"d/m/y" }} </div>
        <div class="col-md-2"> {{ shift.clock_in|date:"H:i" }} - {{ shift.clock_out|date:"H:i" }} </div>
       
        
    </div>
    <hr>
    {% endfor %}

    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-2"> </div>
        <div class="col-md-2"> </div>
        
        <div class="col-md-3"> </div>

    </div>
    <hr>

    {% endfor %}
</div>
</div>

{% endblock content %}

hoursCalc/templates/hoursCalc/shift_detail.html
{% extends './base.html' %}

{% block content %}

<h1>Detalhe do turno</h1>

<h5>{{ shift.name }}</h5>
<h5>Data: {{ shift.date|date:"d/m/y" }}</h5>
<h5>inicio: {{ shift.clock_in|date:"H:i" }} - parada: {{ shift.clock_out|date:"H:i"}}</h5>
<h5>descrição: {{shift.description}}</h5>

{% endblock content %}

hoursCalc/templates/hoursCalc/update_shift.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
  {{ message }}
</div>
{% endfor %}
{% endif %}

<div class="container">

  <h2 class="account-heading">{{ user.username}}</h2>
  <p class="text-secondary">{{ user.email }}</p>
</div>
<div class="container">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-botton mb-4">Mudar</legend>
      {{ shift_form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Atualizar</button>
    </div>
  </form>
</div>

{% endblock content %}